version: '3.8'
services:
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:6.0.7-alpine
    env_file:
      - ./.env
    ports:
      - 6379:6379
