version: '3.8'
services:
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:6.0.7-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 6379:6379
#  mongo:
#    container_name: ${MONGO_CONTAINER_NAME}
#    image: mongo
#    restart: always
#    env_file:
#      - ./.env
#    ports:
#    - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
