export const APP_LOADING_DECR = 'APP_LOADING_DECR';
export const APP_LOADING_INC = 'APP_LOADING_INC';
export const APP_SET_HOC = 'APP_SET_HOC';
export const APP_SET_LANGUAGE_ID = 'APP_SET_LANGUAGE_ID';
export const APP_SET_ALTERNATE = 'APP_SET_ALTERNATE';

export const CATEGORY_SET_BRAND_TREE = 'CATEGORY_SET_BRAND_TREE';
export const CATEGORY_FETCH_BRAND_TREE = 'CATEGORY_FETCH_BRAND_TREE';
