export const APP_LOADING_DECR = 'APP_LOADING_DECR';
export const APP_LOADING_INC = 'APP_LOADING_INC';
export const APP_SET_HOC = 'APP_SET_HOC';
export const APP_SET_LANGUAGE_ID = 'APP_SET_LANGUAGE_ID';
export const APP_SET_ALTERNATE = 'APP_SET_ALTERNATE';

export const CATEGORY_SET_LIST = 'CATEGORY_SET_LIST';
export const CATEGORY_SET_INFO = 'CATEGORY_SET_INFO';
export const CATEGORY_SET_LIST_STATE = 'CATEGORY_SET_LIST_STATE';
export const CATEGORY_FETCH_LIST = 'CATEGORY_FETCH_LIST';

export const BC_SET_LIST = 'BC_SET_LIST';
